// src/components/terminal/prompt-input.vue
<template>
  <!-- Prompt & user input -->
  <div class="prompt-input">
    <form v-on:submit.prevent="submit">
      <input
        ref="input"
        id="input_field"
        name="cmd"
        v-model="input"
        v-on:input="onInput"
        v-on:keydown.tab.prevent="next"
        v-on:keydown.enter.prevent="onEnter"
        v-on:keydown.esc.prevent="dismiss"
        v-on:keydown.up.prevent="previousCommand"
        v-on:keydown.down.prevent="nextCommand"
        type="text"
        autocomplete="off"
        spellcheck="false"
      />
    </form>
    <suggestions
      v-bind:suggestions="termSuggestions"
      v-bind:suggestionIndex="index"
      v-bind:show="showSuggestions"
      v-on:select="accept"
    />
  </div>
</template>

<script>
import suggestions from "./suggestions.vue";

const HISTORY_LIMIT = 50;

export default {
  name: "promptInput",
  data() {
    return {
      input: "",
      index: -1,
      showSuggestions: false,
      history: [],
      historyIndex: -1,
    };
  },
  props: {
    termSuggestions: {
      type: Array,
      default: () => [],
    },
  },
  components: {
    suggestions,
  },
  mounted() {
    this.focus();
  },
  methods: {
    focus() {
      if (this.$refs.input) {
        this.$refs.input.focus({ preventScroll: true });
      }
    },
    onInput() {
      this.$emit("input", this.input);
      this.index = -1;
      this.showSuggestions = false;
      this.historyIndex = -1;
    },
    submit() {
      const value = this.input;
      if (value.trim().length > 0) {
        this.history.push(value);
        if (this.history.length > HISTORY_LIMIT) {
          this.history.shift();
        }
      }
      this.historyIndex = -1;
      this.index = -1;
      this.showSuggestions = false;
      this.input = "";
      this.$emit("submit", value);
    },
    onEnter() {
      // enter accepts the highlighted suggestion, otherwise it runs the command
      if (this.showSuggestions && this.index >= 0) {
        this.accept(this.termSuggestions[this.index]);
        return;
      }
      this.submit();
    },
    next() {
      if (this.termSuggestions.length == 0) return;
      if (!this.showSuggestions) {
        this.showSuggestions = true;
        this.index = 0;
        // a single match needs no cycling, take it right away
        if (this.termSuggestions.length == 1) {
          this.accept(this.termSuggestions[0]);
        }
        return;
      }
      this.index = (this.index + 1) % this.termSuggestions.length;
    },
    accept(suggestion) {
      if (suggestion === undefined) return;
      this.input = this.getCompletedInput(this.input).concat(suggestion);
      this.index = -1;
      this.showSuggestions = false;
      this.$emit("input", this.input);
      this.focus();
    },
    dismiss() {
      this.index = -1;
      this.showSuggestions = false;
    },
    /* Everything up to and including the last space or separator, i.e. the
       part of the input that autocompletion must not overwrite. */
    getCompletedInput(input) {
      const last = Math.max(input.lastIndexOf(" "), input.lastIndexOf("/"));
      return last == -1 ? "" : input.substring(0, last + 1);
    },
    previousCommand() {
      if (this.history.length == 0) return;
      this.historyIndex =
        this.historyIndex == -1
          ? this.history.length - 1
          : Math.max(0, this.historyIndex - 1);
      this.input = this.history[this.historyIndex];
      this.$emit("input", this.input);
    },
    nextCommand() {
      if (this.historyIndex == -1) return;
      if (this.historyIndex >= this.history.length - 1) {
        this.historyIndex = -1;
        this.input = "";
      } else {
        this.historyIndex += 1;
        this.input = this.history[this.historyIndex];
      }
      this.$emit("input", this.input);
    },
  },
};
</script>

<style>
.form-wrapper {
  width: auto;
  overflow: hidden;
}

#input_field {
  width: 100%;
  outline: none !important;
  background: none;
  border: none;
  color: var(--fg);
  font-family: inherit;
  font-size: 1em;
}

form {
  display: inline;
}
</style>

// components/terminal/PromptInput.tsx
'use client';

import { useState, useEffect, useRef } from 'react';
import Suggestions from './Suggestions';

interface PromptInputProps {
  termSuggestions: string[];
  onInput: (value: string) => void;
  onSubmit: (value: string) => void;
}

export default function PromptInput({ termSuggestions, onInput, onSubmit }: PromptInputProps) {
  const [input, setInput] = useState('');
  const [index, setIndex] = useState(-1);
  const [showSuggestions, setShowSuggestions] = useState(false);
  const inputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    inputRef.current?.focus();
  }, []);

  const handleInput = (e: React.ChangeEvent<HTMLInputElement>) => {
    const value = e.target.value;
    setInput(value);
    onInput(value);
    setIndex(-1);
  };

  const handleKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === 'Tab') {
      e.preventDefault();
      if (termSuggestions.length === 0) return;
      if (!showSuggestions) {
        setShowSuggestions(true);
        setIndex(0);
      } else {
        if (termSuggestions.length === 1) {
          handleEnter(e);
        } else {
          setIndex((index + 1) % termSuggestions.length);
        }
      }
    } else if (e.key === 'Enter') {
      e.preventDefault();
      handleEnter(e);
    }
  };

  const handleEnter = (e: React.KeyboardEvent) => {
    if (index === -1) {
      onSubmit(input);
      setInput('');
      setShowSuggestions(false);
    } else {
      const completedInput = getCompletedInput(input);
      let newInput = completedInput + termSuggestions[index];
      if (completedInput.length > 0) {
        newInput += '/';
      } else {
        newInput += ' ';
      }
      setInput(newInput);
      onInput(newInput);
      setIndex(-1);
      setShowSuggestions(false);
    }
  };

  const getCompletedInput = (input: string) => {
    const spaceInd = input.lastIndexOf(' ');
    const sepInd = input.lastIndexOf('/');
    const last = spaceInd > sepInd ? spaceInd : sepInd;
    if (last === -1) {
      return '';
    } else {
      return input.substring(0, last + 1);
    }
  };

  return (
    <div>
      <form style={{ display: 'inline' }}>
        <input
          ref={inputRef}
          id="input_field"
          name="cmd"
          value={input}
          onChange={handleInput}
          onKeyDown={handleKeyDown}
          type="text"
          autoFocus
          autoComplete="off"
          style={{
            width: '100%',
            outline: 'none',
            background: 'none',
            border: 'none',
            color: '#fff',
            fontSize: '1em',
          }}
        />
      </form>
      <Suggestions
        suggestions={termSuggestions}
        suggestionIndex={index}
        show={showSuggestions}
      />
    </div>
  );
}
