// src/components/filemanager/filemanager.vue
<template>
  <div
    id="filemanager"
    tabindex="0"
    ref="filemanager"
    v-on:keydown="onKey"
    v-on:click="focus"
  >
    <div class="wrapper">
      <ul>
        <li
          v-for="(node, index) in content"
          v-bind:key="node.type + node.name"
          v-on:click="enterNode(node)"
          v-bind:class="{
            selected: index == selected,
            marked: markedRemove.indexOf(node.name) != -1,
            directory: node.type == 'directory',
            file: node.type == 'file',
          }"
        >
          {{ node.name }}
        </li>
      </ul>
      <div class="fm-prompt-wrapper" v-if="promptActive">
        <prompt
          v-bind:label="type"
          type="text"
          v-bind:placeholder="placeholders[type]"
          v-on:submit="onSubmit"
          v-on:cancel="cancel"
          ref="filePrompt"
        ></prompt>
      </div>
      <div class="status-bar">
        <span class="position">{{ content.length ? selected + 1 : 0 }}/{{ content.length }}</span>
        <span class="wd">{{ dirname }}</span>
        <span class="fm-error" v-if="error">{{ error }}</span>
        <span class="filter" v-if="filter.length > 0">filter: {{ filter }}</span>
      </div>
    </div>
  </div>
</template>

<script>
import prompt from "./prompt";

export default {
  name: "filemanager",
  data: function () {
    return {
      selected: 0,
      promptActive: false,
      type: "",
      filter: "",
      error: "",
      placeholders: {
        touch: "filename url",
        mkdir: "name",
        search: "string",
        cd: "directory",
      },
      markedRemove: [],
    };
  },
  components: {
    prompt,
  },
  mounted: function () {
    this.focus();
  },
  watch: {
    // the selection must stay inside the list when it shrinks or we navigate
    content: function (newContent) {
      if (this.selected > newContent.length - 1) {
        this.selected = Math.max(0, newContent.length - 1);
      }
    },
  },
  methods: {
    focus: function () {
      if (!this.promptActive && this.$refs.filemanager) {
        // without preventScroll the browser scrolls the whole page to the
        // focused window, which pushes the other windows out of view
        this.$refs.filemanager.focus({ preventScroll: true });
      }
    },
    onKey: function (event) {
      if (this.promptActive || event.ctrlKey || event.metaKey || event.altKey) {
        return;
      }
      const actions = {
        ArrowLeft: this.leave,
        h: this.leave,
        ArrowDown: this.down,
        j: this.down,
        ArrowUp: this.up,
        k: this.up,
        ArrowRight: this.enter,
        l: this.enter,
        Enter: this.enter,
        f: () => this.openPrompt("touch"),
        n: () => this.openPrompt("mkdir"),
        "/": () => this.openPrompt("search"),
        ":": () => this.openPrompt("cd"),
        ";": () => this.openPrompt("cd"),
        d: this.mark,
        p: this.removeMarked,
        Escape: this.cancel,
      };
      const action = actions[event.key];
      if (action) {
        event.preventDefault();
        this.error = "";
        action();
      }
    },
    leave: function () {
      this.changeDirectory("..");
    },
    enter: function () {
      const node = this.content[this.selected];
      if (node) {
        this.enterNode(node);
      }
    },
    enterNode: function (node) {
      if (!node) return;
      if (node.type == "directory") {
        this.changeDirectory(node.name);
      } else {
        window.open(node.url, "_blank", "noopener");
      }
    },
    changeDirectory: function (name) {
      const res = this.fs.cd(this.wd, [name]);
      if (res.directory) {
        // the working directory lives in the store, it cannot be assigned here
        this.$store.dispatch("updateWorkingDirectory", res.directory);
        this.selected = 0;
        this.filter = "";
        this.markedRemove = [];
      } else {
        this.showErrors(res);
      }
    },
    down: function () {
      if (this.content.length == 0) return;
      this.selected = (this.selected + 1) % this.content.length;
    },
    up: function () {
      if (this.content.length == 0) return;
      this.selected =
        this.selected > 0 ? this.selected - 1 : this.content.length - 1;
    },
    openPrompt: function (type) {
      this.type = type;
      this.promptActive = true;
    },
    /* Marking is by name, an index would point at a different entry as soon
       as the listing changes. */
    mark: function () {
      const node = this.content[this.selected];
      if (!node) return;
      const index = this.markedRemove.indexOf(node.name);
      if (index == -1) {
        this.markedRemove.push(node.name);
      } else {
        this.markedRemove.splice(index, 1);
      }
    },
    cancel: function () {
      this.promptActive = false;
      this.type = "";
      this.filter = "";
      this.markedRemove = [];
      this.$nextTick(this.focus);
    },
    removeMarked: function () {
      const names = this.markedRemove.slice();
      let changed = false;
      names.forEach((name) => {
        const node = this.content.filter((n) => n.name == name)[0];
        if (!node) return;
        const res =
          node.type == "file"
            ? this.fs.rm(this.wd, [name])
            : this.fs.rmdir(this.wd, [name]);
        changed = changed || res.success;
        this.showErrors(res);
      });
      this.markedRemove = [];
      this.selected = 0;
      if (changed) {
        this.persist();
      }
    },
    onSubmit: function (value) {
      let res;
      switch (this.type) {
        case "touch":
          res = this.fs.touch(this.wd, value);
          break;
        case "mkdir":
          res = this.fs.mkdir(this.wd, value);
          break;
        case "search":
          this.filter = value;
          this.selected = 0;
          break;
        case "cd":
          this.changeDirectory(value);
          break;
      }
      if (res) {
        this.showErrors(res);
        if (res.success) {
          this.persist();
        }
      }
      this.type = "";
      this.promptActive = false;
      this.$nextTick(this.focus);
    },
    /* Writes the tree back into the store, which persists it to local storage.
       Without this every change was lost on the next reload. */
    persist: function () {
      this.$store.dispatch("updateFileTree", this.fs);
    },
    showErrors: function (res) {
      if (res && res.messages && res.messages.length > 0) {
        this.error = res.messages[0].value;
      }
    },
  },
  computed: {
    fs() {
      return this.$store.state.fileTree;
    },
    wd() {
      return this.$store.state.workingDirectory;
    },
    content: function () {
      if (!this.wd || !this.wd.getChildren) {
        return [];
      }
      let content = this.wd.getChildren().map((c) => ({
        name: c.getName(),
        type: "directory",
      }));
      content = content.concat(
        this.wd.getFiles().map((f) => ({
          name: f.getName(),
          type: "file",
          url: f.getUrl(),
        }))
      );
      if (this.filter.length > 0) {
        const filter = this.filter.toLowerCase();
        return content.filter((n) => n.name.toLowerCase().indexOf(filter) != -1);
      }
      return content;
    },
    dirname: function () {
      return this.wd && this.wd.getPath ? this.wd.getPath() : "";
    },
  },
};
</script>

<style>
#filemanager {
  height: 100%;
  outline: none;
}

.wrapper {
  position: relative;
  width: 100%;
  height: 100%;
  display: flex;
  overflow: hidden;
}

#filemanager ul {
  list-style: none;
  padding: 0;
  margin: 0;
  width: 100%;
  overflow-y: auto;
  scrollbar-width: none;
  max-height: calc(100% - 22px);
}

.directory {
  cursor: pointer;
  color: var(--cyan);
}
.file {
  cursor: pointer;
  color: var(--yellow);
}

.directory.selected {
  background-color: var(--cyan);
  color: var(--dark);
}
.file.selected {
  background-color: var(--yellow);
  color: var(--dark);
}

.status-bar {
  position: absolute;
  bottom: 0;
  height: 22px;
  width: 100%;
  font-size: 0.8rem;
  line-height: 22px;
  color: var(--dark);
  background-color: var(--red);
  overflow: hidden;
  white-space: nowrap;
}

.filter {
  float: right;
}

.fm-error {
  margin-left: 1rem;
}

/* has to beat .directory.selected / .file.selected, an entry can be both */
.directory.marked,
.file.marked,
.directory.selected.marked,
.file.selected.marked {
  background-color: var(--red);
  color: var(--dark);
}
.wd {
  margin-left: 1rem;
}
.fm-prompt-wrapper {
  position: absolute;
  bottom: 22px;
  width: 100%;
  height: 22px;
  margin: auto;
  overflow: hidden;
}
</style>

// components/widgets/FileManager.tsx
'use client';

import { useState, useEffect, useRef } from 'react';
import { useStore } from '@/lib/store';
import FileManagerPrompt from '../filemanager/Prompt';

export default function FileManager() {
  const { fileTree: fs, workingDirectory: wd, updateFileTree, updateWorkingDirectory } = useStore();
  const [selected, setSelected] = useState(0);
  const [promptActive, setPromptActive] = useState(false);
  const [type, setType] = useState('');
  const [filter, setFilter] = useState('');
  const [input, setInput] = useState('');
  const [markedRemove, setMarkedRemove] = useState<number[]>([]);
  const filemanagerRef = useRef<HTMLDivElement>(null);

  const placeholders: Record<string, string> = {
    touch: 'filename url',
    mkdir: 'name',
    search: 'string',
    cd: 'directory',
  };

  useEffect(() => {
    filemanagerRef.current?.focus();
  }, []);

  if (!fs || !wd) {
    return <div className="w-full h-full bg-[var(--bg)] rounded-lg p-4" style={{ color: 'var(--fg)' }}>Loading...</div>;
  }

  const content = (() => {
    let items: Array<{ name: string; type: 'directory' | 'file'; url?: string }> = [];
    const children = wd.getChildren();
    if (children) {
      items = items.concat(
        children.map((c: any) => ({
          name: c.getName(),
          type: 'directory' as const,
        }))
      );
    }
    items = items.concat(
      wd.getFiles().map((f: any) => ({
        name: f.getName(),
        type: 'file' as const,
        url: f.getUrl(),
      }))
    );
    if (filter.length > 0) {
      return items.filter((n) => n.name.indexOf(filter) !== -1);
    }
    return items;
  })();

  const dirname = wd.getPath ? wd.getPath() : '~';

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (promptActive) return;

    switch (e.key) {
      case 'ArrowLeft':
        e.preventDefault();
        leave();
        break;
      case 'ArrowDown':
        e.preventDefault();
        down();
        break;
      case 'ArrowUp':
        e.preventDefault();
        up();
        break;
      case 'ArrowRight':
      case 'Enter':
        e.preventDefault();
        enter();
        break;
      case 'f':
        onInput('touch');
        break;
      case 'n':
        onInput('mkdir');
        break;
      case 'c':
        onInput('cd');
        break;
      case 'd':
        remove();
        break;
      case 'p':
        paste();
        break;
      case 'Escape':
        e.preventDefault();
        cancel();
        break;
    }
  };

  const leave = () => {
    if (promptActive) return;
    const res = fs.cd(wd, '..');
    if (res.directory) {
      updateWorkingDirectory(res.directory);
      setSelected(0);
    }
  };

  const enter = () => {
    if (promptActive) return;
    const node = content[selected];
    if (!node) return;
    enterClicked(node);
  };

  const enterClicked = (node: { name: string; type: string; url?: string }) => {
    if (node.type === 'directory') {
      const res = fs.cd(wd, node.name);
      if (res.directory) {
        updateWorkingDirectory(res.directory);
        setSelected(0);
      }
    } else if (node.type === 'file' && node.url) {
      window.open(node.url, '_blank');
    }
  };

  const down = () => {
    if (promptActive) return;
    setSelected((selected + 1) % content.length);
  };

  const up = () => {
    if (promptActive) return;
    setSelected(selected > 0 ? selected - 1 : content.length - 1);
  };

  const onInput = (inputType: string) => {
    if (promptActive) return;
    setType(inputType);
    setPromptActive(true);
  };

  const remove = () => {
    if (promptActive) return;
    if (markedRemove.indexOf(selected) === -1) {
      setMarkedRemove([...markedRemove, selected]);
    } else {
      setMarkedRemove(markedRemove.filter((i) => i !== selected));
    }
  };

  const cancel = () => {
    setPromptActive(false);
    setFilter('');
    filemanagerRef.current?.focus();
  };

  const paste = () => {
    for (const index of markedRemove) {
      const node = content[index];
      if (node.type === 'file') {
        fs.rm(wd, [node.name]);
      } else if (node.type === 'directory') {
        fs.rmdir(wd, [node.name]);
      }
    }
    updateFileTree(fs);
    setMarkedRemove([]);
    setSelected(0);
  };

  const onSubmit = (value: string) => {
    switch (type) {
      case 'touch':
        fs.touch(wd, value.split(' '));
        break;
      case 'mkdir':
        fs.mkdir(wd, value);
        break;
      case 'search':
        setFilter(value);
        break;
      case 'cd':
        const node = content.filter((n) => n.name === value)[0];
        if (node) enterClicked(node);
        break;
    }
    updateFileTree(fs);
    setType('');
    setPromptActive(false);
    filemanagerRef.current?.focus();
  };

  return (
    <div
      id="filemanager"
      ref={filemanagerRef}
      tabIndex={0}
      onKeyDown={handleKeyDown}
      className="w-full h-full bg-[var(--bg)] rounded-lg"
      style={{ color: 'var(--fg)', outline: 'none' }}
    >
      <div className="wrapper" style={{ position: 'relative', width: '100%', height: '100%', display: 'flex' }}>
        <ul style={{ listStyle: 'none', padding: 0, margin: 0 }}>
          {content.map((node, index) => (
            <li
              key={index}
              onClick={() => enterClicked(node)}
              style={{
                cursor: 'pointer',
                backgroundColor:
                  index === selected
                    ? node.type === 'directory'
                      ? 'var(--cyan)'
                      : 'var(--yellow)'
                    : markedRemove.indexOf(index) !== -1
                    ? 'var(--red)'
                    : 'transparent',
                color:
                  index === selected
                    ? 'var(--dark)'
                    : markedRemove.indexOf(index) !== -1
                    ? 'var(--dark)'
                    : node.type === 'directory'
                    ? 'var(--cyan)'
                    : 'var(--yellow)',
              }}
            >
              {node.name}
            </li>
          ))}
        </ul>
        {promptActive && (
          <div
            className="fm-prompt-wrapper"
            style={{
              position: 'absolute',
              bottom: '22px',
              width: '100%',
              height: '22px',
              margin: 'auto',
              overflow: 'hidden',
            }}
          >
            <FileManagerPrompt
              label={type}
              placeholder={placeholders[type] || ''}
              onSubmit={onSubmit}
            />
          </div>
        )}
        <div
          className="status-bar"
          style={{
            position: 'absolute',
            bottom: 0,
            height: '22px',
            width: '100%',
            color: 'var(--dark)',
            backgroundColor: 'var(--red)',
          }}
        >
          <span className="position" style={{ marginLeft: '1rem' }}>
            {selected + 1}/{content.length}
          </span>
          <span className="wd" style={{ marginLeft: '1rem' }}>
            {dirname}
          </span>
          {filter.length > 0 && (
            <span className="filter" style={{ float: 'right' }}>
              filter: {filter}
            </span>
          )}
        </div>
      </div>
    </div>
  );
}
