// components/terminal/Suggestions.tsx
'use client';

interface SuggestionsProps {
  suggestions: string[];
  suggestionIndex: number;
  show: boolean;
  onSelect?: (suggestion: string) => void;
}

export default function Suggestions({ suggestions, suggestionIndex, show, onSelect }: SuggestionsProps) {
  if (!show || suggestions.length === 0) return null;

  return (
    <ul
      id="suggestions"
      style={{
        columnCount: 3,
        columnWidth: '100px',
        paddingLeft: 0,
        listStyle: 'none',
      }}
    >
      {suggestions.map((sug, index) => (
        <li
          key={index}
          className="suggestion"
          onClick={() => onSelect?.(sug)}
          style={{
            backgroundColor: index === suggestionIndex ? 'var(--pink)' : 'transparent',
            color: index === suggestionIndex ? 'var(--dark)' : 'inherit',
            cursor: 'pointer',
          }}
        >
          {sug}
        </li>
      ))}
    </ul>
  );
}

// src/components/terminal/suggestions.vue
<template>
  <ul id="suggestions" v-if="show && suggestions.length > 0">
    <li
      v-for="(sug, index) in suggestions"
      v-bind:class="{ activeSuggestion: index == suggestionIndex }"
      v-bind:key="sug + index"
      v-on:click="$emit('select', sug)"
      class="suggestion"
    >
      {{ sug }}
    </li>
  </ul>
</template>

<script>
export default {
  name: "suggestions",
  props: {
    suggestions: {
      type: Array,
      default: () => [],
    },
    suggestionIndex: Number,
    show: Boolean,
  },
};
</script>

<style>
#suggestions li {
  list-style: none;
  cursor: pointer;
}

#suggestions {
  column-count: 3;
  column-width: 100px;
  padding-left: 0;
  margin: 0;
}

.activeSuggestion {
  background-color: var(--accent_1);
  color: var(--bg);
}
</style>
