// components/widgets/Terminal.tsx
'use client';

import { useState, useEffect, useCallback } from 'react';
import { useStore } from '@/lib/store';
import Prompt from '../terminal/Prompt';
import TermOut from '../terminal/TermOut';
import { newResponse } from '@/lib/components/response';
import { log } from '@/lib/components/logger';
import { get_browser_info } from '@/lib/components/utility';

export default function Terminal() {
  const { fileTree: fs, workingDirectory: wd, updateFileTree, updateWorkingDirectory } = useStore();
  const [out, setOut] = useState({ dirs: [] as string[], files: [] as Array<{ name: string; url: string }>, messages: [] as Array<{ type: string; value: string; css?: React.CSSProperties }> });
  const [suggestions, setSuggestions] = useState<string[]>([]);
  const [windowHeight, setWindowHeight] = useState(100);
  const [windowWidth, setWindowWidth] = useState(100);
  const [commands, setCommands] = useState<any>({});

  useEffect(() => {
    const handleResize = () => {
      setWindowHeight(window.innerHeight);
      setWindowWidth(window.innerWidth);
    };
    window.addEventListener('resize', handleResize);
    handleResize();
    buildCommands();
    return () => window.removeEventListener('resize', handleResize);
  }, []);

  const buildCommands = useCallback(() => {
    const cmds: any = {
      clear: () => newResponse(),
      fetch: () => {
        const res = newResponse();
        res.messages.push({
          type: 'value',
          value: 'OS > ' + window.navigator.platform,
          css: { color: 'var(--orange)' },
        });
        res.messages.push({
          type: 'value',
          value: 'Kernel > bashrc v1.0.1',
          css: { color: 'var(--yellow)' },
        });
        const seconds = Math.floor(Math.random() * 60);
        const minutes = Math.floor(Math.random() * 60);
        res.messages.push({
          type: 'value',
          value: `Uptime > ${minutes} minutes - ${seconds} seconds`,
          css: { color: 'var(--green)' },
        });
        res.messages.push({
          type: 'value',
          value: 'Resolution > ' + windowWidth + 'x' + windowHeight,
          css: { color: 'var(--pink)' },
        });
        res.messages.push({
          type: 'value',
          value: 'DE > ' + get_browser_info().name,
          css: { color: 'var(--darkblue)' },
        });
        return res;
      },
      pwd: () => {
        const res = newResponse();
        if (wd) {
          res.messages.push({ type: 'value', value: wd.getName() });
        }
        return res;
      },
      echo: (args: string[]) => {
        const res = newResponse();
        res.messages.push({ type: 'value', value: args.join(' ') });
        return res;
      },
      locate: (args: string[]) => {
        if (args[0]) {
          window.open('https://duckduckgo.com/' + args.join(' '));
        } else {
          const res = newResponse();
          res.messages.push({ type: 'error', value: 'Please enter a valid search query' });
          return res;
        }
      },
      open: (args: string[]) => {
        log('open', args);
        const res = newResponse();
        if (!args[0]) {
          res.messages.push({ type: 'error', value: 'open: missing operand' });
          return res;
        }
        if (!fs || !wd) return res;
        const file = fs.getNode(wd, args[0]);
        if (!file) {
          res.messages.push({
            type: 'error',
            value: `open: cannot open '${args[0]}': No such file or directory`,
          });
          return res;
        }
        if (file.url) {
          window.location.href = file.url;
        }
        return res;
      },
      getMethods: () => {
        return Object.keys(cmds).filter((m) => typeof cmds[m] === 'function' && m !== 'getMethods');
      },
    };
    setCommands(cmds);
  }, [wd, windowWidth, windowHeight]);

  const onCommand = (input: string) => {
    suggest(input);
  };

  const onCommandSubmit = (com: string) => {
    setOut({ dirs: [], files: [], messages: [] });
    const parts = com.split(' ');
    const command = parts[0];
    const args = parts.slice(1);

    try {
      if (commands[command]) {
        const response = commands[command](args);
        if (response) {
          setOut({
            dirs: response.dirs || [],
            files: response.files || [],
            messages: response.messages || [],
          });
        }
        return;
      }

      if (!fs || !wd) return;
      const res = fs.call(command, wd, args);
      if (res) {
        if (res.success) {
          updateFileTree(fs);
        }
        if (res.directory) {
          updateWorkingDirectory(res.directory);
        } else {
          setOut({
            dirs: res.dirs || [],
            files: res.files || [],
            messages: res.messages || [],
          });
        }
      }
    } catch (e) {
      log('error', String(e), 'red');
      const res = newResponse();
      res.messages.push({
        type: 'error',
        value: `bashrc: command not found: ${command}`,
      });
      setOut({
        dirs: [],
        files: [],
        messages: res.messages,
      });
    }
  };

  const suggest = (input: string) => {
    log('input', input, 'green');
    if (input.length === 0) {
      setSuggestions([]);
      return;
    }
    if (input.indexOf(' ') !== -1) {
      log('Suggesting', 'files', 'green');
      suggestFiles(input);
    } else {
      log('Suggesting', 'commands', 'green');
      suggestCommands(input);
    }
  };

  const suggestCommands = (input: string) => {
    if (!fs || !wd) return;
    const cmdMethods = commands.getMethods ? commands.getMethods() : [];
    const files = wd.getFileNames();
    const all = cmdMethods.concat(fs.api()).concat(files);
    setSuggestions(all.filter((c: string) => c.substr(0, input.length) === input));
  };

  const suggestFiles = (input: string) => {
    if (!fs || !wd) return;
    const command = input.split(' ')[0] + ' ';
    let path = input.split(' ').slice(1).join(' ');
    let content: string[];

    if (path.indexOf(fs.separator) !== -1) {
      path = path.substr(0, path.lastIndexOf(fs.separator));
      const node = fs.getNode(wd, path);
      if (node) {
        content = node.getChildrenNames();
      } else {
        content = [];
      }
    } else {
      content = wd.getChildrenNames();
    }
    setSuggestions(content);
  };

  const wdPath = wd ? wd.getPath() : '~';

  return (
    <div className="w-full h-full bg-[var(--bg)] rounded-lg p-4 font-mono text-sm" style={{ opacity: 0.95, color: 'var(--fg)' }}>
      <Prompt
        wd={wdPath}
        suggestions={suggestions}
        onInput={onCommand}
        onSubmit={onCommandSubmit}
      />
      <TermOut out={out} onCd={onCommandSubmit} />
    </div>
  );
}

// src/components/terminal/terminal.vue
<template>
  <div class="terminal" v-on:click="focusInput">
    <prompt
      v-on:input="onCommand"
      v-on:submit="onCommandSubmit"
      v-bind:wd="wdPath"
      v-bind:suggestions="suggestions"
    />
    <term-out v-bind:out="out" v-on:cd="onCommandSubmit" />
  </div>
</template>

<script>
import prompt from "./prompt.vue";
import termOut from "./term-out.vue";
import { newResponse } from "../response";
import { log } from "../logger";
import { get_browser_info } from "../utility";

export default {
  name: "terminal",
  components: {
    prompt,
    termOut,
  },
  data: function () {
    return {
      out: { dirs: [], files: [], messages: [] },
      suggestions: [],
      uptimeStart: new Date().getTime(),
    };
  },
  computed: {
    fs() {
      return this.$store.state.fileTree;
    },
    wd() {
      return this.$store.state.workingDirectory;
    },
    wdPath() {
      return this.wd ? this.wd.getPath() : "";
    },
    /* Commands that are not part of the file system itself. They are defined
       here (and not in data) so that `this` is the component. */
    builtins() {
      return {
        help: () => {
          const res = newResponse();
          res.messages.push({
            type: "value",
            value: `commands: ${this.commandNames.join(", ")}`,
          });
          res.messages.push({
            type: "value",
            value: "tab completes, up/down cycles through the history",
          });
          return res;
        },
        clear: () => newResponse(),
        fetch: () => {
          const res = newResponse();
          const uptime = Math.floor((Date.now() - this.uptimeStart) / 1000);
          res.messages.push({
            type: "value",
            value: "OS > " + window.navigator.platform,
            css: { color: "var(--orange)" },
          });
          res.messages.push({
            type: "value",
            value: "Kernel > bashrc v2.0.0",
            css: { color: "var(--yellow)" },
          });
          res.messages.push({
            type: "value",
            value: `Uptime > ${Math.floor(uptime / 60)} minutes - ${uptime % 60} seconds`,
            css: { color: "var(--green)" },
          });
          res.messages.push({
            type: "value",
            value: `Resolution > ${window.innerWidth}x${window.innerHeight}`,
            css: { color: "var(--pink)" },
          });
          res.messages.push({
            type: "value",
            value: "DE > " + get_browser_info().name,
            css: { color: "var(--darkblue)" },
          });
          return res;
        },
        pwd: () => {
          const res = newResponse();
          res.messages.push({ type: "value", value: this.wdPath });
          return res;
        },
        echo: (args) => {
          const res = newResponse();
          res.messages.push({ type: "value", value: args.join(" ") });
          return res;
        },
        locate: (args) => {
          const res = newResponse();
          if (!args[0]) {
            return res.error("locate: please enter a search query");
          }
          window.open(
            `https://duckduckgo.com/?q=${encodeURIComponent(args.join(" "))}`,
            "_blank"
          );
          return res;
        },
        open: (args) => {
          const res = newResponse();
          if (!args[0]) {
            return res.error("open: missing operand");
          }
          const file = this.fs.getNode(this.wd, args[0]);
          if (!file) {
            return res.error(
              `open: cannot open '${args[0]}': No such file or directory`
            );
          }
          if (!file.url) {
            return res.error(`open: '${args[0]}' is a directory`);
          }
          window.open(file.url, "_blank");
          return res;
        },
      };
    },
    commandNames() {
      return Object.keys(this.builtins).concat(this.fs ? this.fs.api() : []);
    },
  },
  methods: {
    /* clicking anywhere in the terminal window should put the cursor back
       into the prompt, like clicking into a real terminal does */
    focusInput: function () {
      const input = this.$el.querySelector("#input_field");
      if (input) {
        input.focus({ preventScroll: true });
      }
    },
    onCommand: function (input) {
      this.suggest(input);
    },
    onCommandSubmit: function (com) {
      this.suggestions = [];
      this.showResponse(newResponse());
      if (!com || com.trim().length == 0) {
        return;
      }

      const parts = com.trim().split(/\s+/);
      const command = parts[0];
      const args = parts.slice(1);

      if (this.builtins[command]) {
        this.showResponse(this.builtins[command](args));
        return;
      }

      const res = this.fs.call(command, this.wd, args);
      if (!res) {
        const notFound = newResponse();
        notFound.error(`bashrc: command not found: ${command}`);
        this.showResponse(notFound);
        return;
      }
      // a command that changed the tree has to be written back to the store
      if (res.success) {
        this.$store.dispatch("updateFileTree", this.fs);
      }
      if (res.directory) {
        this.$store.dispatch("updateWorkingDirectory", res.directory);
      }
      this.showResponse(res);
    },
    showResponse: function (res) {
      if (!res) {
        return;
      }
      this.out = {
        dirs: res.dirs || [],
        files: res.files || [],
        messages: res.messages || [],
      };
    },
    suggest: function (input) {
      if (!input || input.length == 0) {
        this.suggestions = [];
        return;
      }
      // a space means the command is typed already and we complete a path
      if (input.indexOf(" ") != -1) {
        this.suggestFiles(input);
      } else {
        this.suggestCommands(input);
      }
    },
    suggestCommands: function (input) {
      const names = this.commandNames.concat(this.wd ? this.wd.getFileNames() : []);
      this.suggestions = names.filter((c) => c.substr(0, input.length) == input);
    },
    suggestFiles: function (input) {
      const path = input.split(/\s+/).slice(1).join(" ");
      let searchDir = this.wd;
      let fragment = path || "";

      if (path.indexOf(this.fs.separator) != -1) {
        const dirPath = path.substr(0, path.lastIndexOf(this.fs.separator));
        fragment = path.substr(path.lastIndexOf(this.fs.separator) + 1);
        searchDir = this.fs.getNode(this.wd, dirPath);
      }
      if (!searchDir || searchDir.url) {
        this.suggestions = [];
        return;
      }
      const content = searchDir
        .getChildrenNames()
        .concat(searchDir.getFileNames());
      this.suggestions = content.filter(
        (c) => c.substr(0, fragment.length) == fragment
      );
    },
  },
};
</script>

<style>
.terminal {
  opacity: 0.95;
  height: 100%;
  display: flex;
  flex-direction: column;
  overflow: hidden;
}
</style>
